// port-lint: source syntect/src/html.rs
package io.github.kotlinmania.syntect.html

import io.github.kotlinmania.syntect.easy.HighlightLines
import io.github.kotlinmania.syntect.escape.escapeHtml
import io.github.kotlinmania.syntect.highlighting.Color
import io.github.kotlinmania.syntect.highlighting.FontStyle
import io.github.kotlinmania.syntect.highlighting.HighlightedSegment
import io.github.kotlinmania.syntect.highlighting.Style
import io.github.kotlinmania.syntect.highlighting.Theme
import io.github.kotlinmania.syntect.parsing.BasicScopeStackOp
import io.github.kotlinmania.syntect.parsing.ParseOp
import io.github.kotlinmania.syntect.parsing.ParseState
import io.github.kotlinmania.syntect.parsing.Scope
import io.github.kotlinmania.syntect.parsing.ScopeStack
import io.github.kotlinmania.syntect.parsing.SyntaxReference
import io.github.kotlinmania.syntect.parsing.SyntaxSet
import io.github.kotlinmania.syntect.util.linesWithEndings

/**
 * Class styling modes for HTML generator.
 */
sealed class ClassStyle {
    /**
     * The classes are the atoms of the scope separated by spaces.
     */
    data object Spaced : ClassStyle()

    /**
     * Like [Spaced], but with a prefix prepended to all classes.
     */
    data class SpacedPrefixed(
        val prefix: String,
    ) : ClassStyle()
}

/**
 * Determines how background color attributes are generated.
 */
sealed class IncludeBackground {
    data object No : IncludeBackground()

    data object Yes : IncludeBackground()

    data class IfDifferent(
        val color: Color,
    ) : IncludeBackground()
}

/**
 * Output HTML for lines of code with `<span>` elements using class names.
 */
class ClassedHTMLGenerator(
    val syntaxReference: SyntaxReference,
    val syntaxSet: SyntaxSet,
    val style: ClassStyle = ClassStyle.Spaced,
) {
    private var openSpans: Int = 0
    private val parseState: ParseState = ParseState(syntaxReference)
    private val scopeStack: ScopeStack = ScopeStack()
    private val htmlBuilder = StringBuilder()

    fun parseHtmlForLineWhichIncludesNewline(line: String) {
        val parsedLine = parseState.parseLine(line, syntaxSet)
        val (formattedLine, delta) = lineTokensToClassedSpans(line, parsedLine, style, scopeStack)
        openSpans += delta
        htmlBuilder.append(formattedLine)
    }

    fun finalize(): String {
        for (i in 0 until openSpans) {
            htmlBuilder.append("</span>")
        }
        return htmlBuilder.toString()
    }

    companion object {
        fun newWithClassStyle(
            syntaxReference: SyntaxReference,
            syntaxSet: SyntaxSet,
            style: ClassStyle,
        ): ClassedHTMLGenerator = ClassedHTMLGenerator(syntaxReference, syntaxSet, style)
    }
}

private fun escapeCssIdentifier(identifier: String): String {
    val sb = StringBuilder(identifier.length)
    for ((i, c) in identifier.withIndex()) {
        if (c in 'a'..'z' || c in 'A'..'Z' || c == '-' || c == '_' || (i > 0 && c in '0'..'9')) {
            sb.append(c)
        } else {
            sb.append("\\${c.code.toString(16)} ")
        }
    }
    return sb.toString()
}

private fun scopeToClasses(
    sb: StringBuilder,
    scope: Scope,
    style: ClassStyle,
) {
    val repo = Scope.globalScopeRepo
    for (i in 0 until scope.len()) {
        val atom = scope.atomAt(i).toInt()
        val atomStr = repo.atomStr(atom)
        if (i != 0) sb.append(' ')
        when (style) {
            is ClassStyle.Spaced -> Unit
            is ClassStyle.SpacedPrefixed -> sb.append(style.prefix)
        }
        sb.append(atomStr)
    }
}

private fun scopeToSelector(
    sb: StringBuilder,
    scope: Scope,
    style: ClassStyle,
) {
    val repo = Scope.globalScopeRepo
    for (i in 0 until scope.len()) {
        val atom = scope.atomAt(i).toInt()
        val atomStr = repo.atomStr(atom)
        sb.append('.')
        val cls =
            when (style) {
                is ClassStyle.Spaced -> atomStr
                is ClassStyle.SpacedPrefixed -> style.prefix + atomStr
            }
        sb.append(escapeCssIdentifier(cls))
    }
}

private fun hex2(v: UByte): String {
    val s = v.toString(16)
    return if (s.length == 1) "0$s" else s
}

private fun writeCssColor(
    sb: StringBuilder,
    c: Color,
) {
    if (c.a != 0xFFu.toUByte()) {
        sb.append("#${hex2(c.r)}${hex2(c.g)}${hex2(c.b)}${hex2(c.a)}")
    } else {
        sb.append("#${hex2(c.r)}${hex2(c.g)}${hex2(c.b)}")
    }
}

/**
 * Creates complete CSS for a given theme.
 */
fun cssForThemeWithClassStyle(
    theme: Theme,
    style: ClassStyle = ClassStyle.Spaced,
): String {
    val css = StringBuilder()
    css.append("/*\n")
    val name = theme.name ?: "unknown theme"
    css.append(" * theme \"$name\" generated by syntect\n")
    css.append(" */\n\n")

    when (style) {
        is ClassStyle.Spaced -> css.append(".code {\n")
        is ClassStyle.SpacedPrefixed -> {
            val cls = escapeCssIdentifier("${style.prefix}code")
            css.append(".$cls {\n")
        }
    }
    theme.settings.foreground?.let { fgc ->
        css.append(" color: #${hex2(fgc.r)}${hex2(fgc.g)}${hex2(fgc.b)};\n")
    }
    theme.settings.background?.let { bgc ->
        css.append(" background-color: #${hex2(bgc.r)}${hex2(bgc.g)}${hex2(bgc.b)};\n")
    }
    css.append("}\n\n")

    for (item in theme.scopes) {
        val selectorBuilder = StringBuilder()
        for (scopeSelector in item.scope.selectors) {
            val scopes = scopeSelector.extractScopes()
            for (k in scopes) {
                scopeToSelector(selectorBuilder, k, style)
                selectorBuilder.append(' ')
            }
            if (selectorBuilder.isNotEmpty() && selectorBuilder.last() == ' ') {
                selectorBuilder.deleteAt(selectorBuilder.length - 1)
            }
            selectorBuilder.append(", ")
        }
        if (selectorBuilder.length >= 2) {
            selectorBuilder.setLength(selectorBuilder.length - 2)
        }
        css.append(selectorBuilder)
        css.append(" {\n")

        item.style.foreground?.let { fg ->
            css.append(" color: #${hex2(fg.r)}${hex2(fg.g)}${hex2(fg.b)};\n")
        }
        item.style.background?.let { bg ->
            css.append(" background-color: #${hex2(bg.r)}${hex2(bg.g)}${hex2(bg.b)};\n")
        }
        item.style.fontStyle?.let { fs ->
            if (fs.contains(FontStyle.UNDERLINE)) css.append("text-decoration: underline;\n")
            if (fs.contains(FontStyle.BOLD)) css.append("font-weight: bold;\n")
            if (fs.contains(FontStyle.ITALIC)) css.append("font-style: italic;\n")
        }
        css.append("}\n")
    }

    return css.toString()
}

/**
 * Result of converting line tokens to classed spans.
 */
data class ClassedSpansResult(
    val html: String,
    val delta: Int,
)

/**
 * Result of starting a highlighted HTML snippet.
 */
data class HighlightedSnippetStart(
    val html: String,
    val background: Color,
)

/**
 * Output HTML for a line of code with `<span>` elements specifying classes.
 */
fun lineTokensToClassedSpans(
    line: String,
    ops: List<ParseOp>,
    style: ClassStyle,
    stack: ScopeStack,
): ClassedSpansResult {
    val s = StringBuilder(line.length + ops.size * 8)
    var curIndex = 0
    var spanDelta = 0
    var spanEmpty = false
    var spanStart = 0

    for (op in ops) {
        val i = op.offset
        if (i > curIndex) {
            spanEmpty = false
            s.append(escapeHtml(line.substring(curIndex, i)))
            curIndex = i
        }
        stack.applyWithHook(op.op) { basicOp, _ ->
            when (basicOp) {
                is BasicScopeStackOp.Push -> {
                    spanStart = s.length
                    spanEmpty = true
                    s.append("<span class=\"")
                    scopeToClasses(s, basicOp.scope, style)
                    s.append("\">")
                    spanDelta++
                }
                is BasicScopeStackOp.Pop -> {
                    if (!spanEmpty) {
                        s.append("</span>")
                    } else {
                        s.setLength(spanStart)
                    }
                    spanDelta--
                    spanEmpty = false
                }
            }
        }
    }
    if (curIndex < line.length) {
        s.append(escapeHtml(line.substring(curIndex, line.length)))
    }
    return ClassedSpansResult(s.toString(), spanDelta)
}

/**
 * Creates a full highlighted HTML snippet for a string.
 */
fun highlightedHtmlForString(
    s: String,
    ss: SyntaxSet,
    syntax: SyntaxReference,
    theme: Theme,
): String {
    val highlighter = HighlightLines(syntax, theme)
    val snippetStart = startHighlightedHtmlSnippet(theme)
    val sb = StringBuilder(snippetStart.html)

    for (line in linesWithEndings(s)) {
        val regions = highlighter.highlightLine(line, ss)
        appendHighlightedHtmlForStyledLine(regions, IncludeBackground.IfDifferent(snippetStart.background), sb)
    }
    sb.append("</pre>\n")
    return sb.toString()
}

/**
 * Output HTML for a line of code with `<span>` elements using inline style attributes.
 */
fun styledLineToHighlightedHtml(
    v: List<HighlightedSegment>,
    bg: IncludeBackground,
): String {
    val sb = StringBuilder()
    appendHighlightedHtmlForStyledLine(v, bg, sb)
    return sb.toString()
}

/**
 * Appends highlighted HTML for a styled line to a StringBuilder.
 */
fun appendHighlightedHtmlForStyledLine(
    v: List<HighlightedSegment>,
    bg: IncludeBackground,
    s: StringBuilder,
) {
    var prevStyle: Style? = null
    for (segment in v) {
        val style = segment.style
        val text = segment.text
        val unifyStyle =
            if (prevStyle != null) {
                style == prevStyle || (style.background == prevStyle.background && text.trim().isEmpty())
            } else {
                false
            }
        if (unifyStyle) {
            s.append(escapeHtml(text))
        } else {
            if (prevStyle != null) {
                s.append("</span>")
            }
            prevStyle = style
            s.append("<span style=\"")
            val includeBg =
                when (bg) {
                    is IncludeBackground.Yes -> true
                    is IncludeBackground.No -> false
                    is IncludeBackground.IfDifferent -> style.background != bg.color
                }
            if (includeBg) {
                s.append("background-color:")
                writeCssColor(s, style.background)
                s.append(";")
            }
            if (style.fontStyle.contains(FontStyle.UNDERLINE)) {
                s.append("text-decoration:underline;")
            }
            if (style.fontStyle.contains(FontStyle.BOLD)) {
                s.append("font-weight:bold;")
            }
            if (style.fontStyle.contains(FontStyle.ITALIC)) {
                s.append("font-style:italic;")
            }
            s.append("color:")
            writeCssColor(s, style.foreground)
            s.append(";\">")
            s.append(escapeHtml(text))
        }
    }
    if (prevStyle != null) {
        s.append("</span>")
    }
}

/**
 * Returns a `<pre style="...">\n` tag with the background color for the theme.
 */
fun startHighlightedHtmlSnippet(t: Theme): HighlightedSnippetStart {
    val c = t.settings.background ?: Color.WHITE
    return HighlightedSnippetStart(
        "<pre style=\"background-color:#${hex2(c.r)}${hex2(c.g)}${hex2(c.b)};\">\n",
        c,
    )
}
